#!/bin/sh
lddep() {
	cd .. 
	./99_enter_buildchroot ldd "$1" 2>/dev/null | awk '{print $3;}' | sed 's,/,,' | grep -v '^$' |grep -v '^/' ;
	cd - >/dev/null
}
set -eux
mkdir -p rootfs/apps
cp entry* rootfs/
cp -a apps rootfs/
mkdir -p rootfs/bin rootfs/dev rootfs/sbin rootfs/proc rootfs/lib rootfs/tmp rootfs/usr rootfs/usr/bin rootfs/usr/sbin rootfs/usr/lib rootfs/usr/share rootfs/usr/share/X11 rootfs/usr/share/X11/xkb
cd build_chroot
cp bin/relayttpd* bin/httpget bin/dropcap-inner bin/dropcap-outer ../rootfs/bin
rm -fr lagun/lagun/renv* lagun/lagun/.Rprofile lagun/lagun/*~ lagun/documentation lagun/lagun/tests lagun/simulat* lagun/lagun/doc 
rsync -av --exclude=.git lagun/lagun ../rootfs/apps/
touch ../rootfs/apps/lagun/no_home_cache
excl=
for i in doc help html examples data demo; do
	excl="$excl "'--exclude=*R/lib/R/library/*/'$i'/*'
done
rsync -a --exclude='*include*' --exclude='*LC_MESSAGES*' --exclude='*.map' --exclude='*R/lib/R/doc*' --exclude='*R/lib/R/share/*' --exclude='*R/share/*' $excl opt ../rootfs/
cp -a bin ../rootfs/
cd .. ; ./99_enter_rootfs /bin/busybox --install ; cd -
ln -sf /bin/busybox ../rootfs/usr/bin/env
cp -a usr/bin/Xvfb ../rootfs/bin/
cp -a usr/bin/xkbcomp ../rootfs/usr/bin/
cp -a lib/ld-musl* ../rootfs/lib/
cp -a usr/share/X11/xkb ../rootfs/usr/share/X11/
cp -a usr/bin/which ../rootfs/usr/bin/
cp -a usr/bin/ttyd ../rootfs/usr/bin/
cp -a usr/bin/strace ../rootfs/usr/bin/
cp usr/bin/lrz usr/bin/lsz ../rootfs/bin/
cp -a usr/lib/libwebsockets-evlib_uv.so ../rootfs/usr/lib/
cp $(lddep /usr/bin/ttyd) ../rootfs/lib
cp $(lddep /usr/bin/strace) ../rootfs/lib
cp $(lddep /usr/bin/Xvfb) ../rootfs/lib
cp $(lddep /usr/bin/which) ../rootfs/lib
cp $(lddep /usr/bin/xkbcomp) ../rootfs/lib
cp $(lddep /opt/R/lib/R/bin/exec/R) ../rootfs/lib
for l in opt/R/lib/R/modules/*; do
	cp $(lddep /$l) ../rootfs/lib
done
for l in libstdc++.so.6 libssl.so.3 libcrypto.so.3 libgcc_s.so.1 libexecinfo.so.1 libcairo.so.2 libgfortran.so.5 libquadmath.so.0 libgsl.so.27 libgslcblas.so.0 ; do
	cp $(find . -name "$l"|head -n 1) ../rootfs/lib
done
cd ..
./99_enter_rootfs chmod -R a+r .
./99_enter_rootfs chmod -R a+x bin sbin usr/bin usr/sbin
./99_enter_rootfs chmod -R a+w tmp 
./99_enter_rootfs tar cv --numeric-owner / |xz -9c > rootfs.tar.xz

