#!/bin/sh
rm -fr rootfs/tmp/* rootfs/tmp/.* rootfs/dev/*
mkdir rootfs/dev rootfs/dev/pts rootfs/etc
for d in urandom random null full zero; do touch rootfs/dev/$d; done
chmod -R a+rwx rootfs/dev/pts
ln -s /dev/pts/ptmx rootfs/dev/ptmx
echo "namserver 127.0.0.1" >rootfs/etc/resolv.conf
echo "127.0.0.1 localhost" > rootfs/etc/hosts
su nobody2 -c "env -i HOME=/tmp PATH=/bin:/sbin:/usr/bin:/usr/sbin \
     unshare -rpmf /bin/sh -c \"for d in urandom random null full zero; do \
								         mount --bind /dev/\\\$d rootfs/dev/\\\$d; \
	      		                done; \
			      					 mount -t devpts -o mode=0600,ptmxmode=0666 none rootfs/dev/pts ; \
								   	 mount -t proc none rootfs/proc ; \
								  	    mount --rbind rootfs rootfs ; \
								  		 pivot_root rootfs rootfs ; \
								 		 cd / ; \
								  		 umount -l / ; \
								       $*\" "   &
x=$?
trap "kill -9 $x ; rm rootfs/dev/*" INT
wait

