#!/bin/sh
unshare -m --mount-proc -p -U -r -f /bin/sh -c "mount --bind rootfs rootfs ; mount -t devpts none rootfs/dev/pts ; mount -t proc none rootfs/proc ; pivot_root rootfs rootfs ; cd / ; umount -l / ; $*"

