#!/bin/sh
rm -rf /tmp/* /tmp/.*
[ -e /proc/self ] || mount -t proc none /proc
cat > /tmp/index.html << EOF
<!doctype html>
<meta name=viewport content=width=device-width>
<title>Shiny</title>
<a target=_blank href=lagun/>LAGUN</a><p>
<a target=_blank href=testapp/>Test application</a><p>
<details><summary>System info</summary>
<pre>
Server started $(date)
EOF
/opt/R/bin/R --vanilla -e "installed.packages()[,'Version']" >> /tmp/index.html
echo "</pre></details><p><a target=_blank href=https://github.com/alex14fr/lagun-shiny-deploy>Server source code</a>" >> /tmp/index.html
mkdir /tmp/cache
Xvfb :999&
sleep 1
args=""
mkdir /tmp/priv
pp=1234
for d in /apps/* ; do
	a=$(basename $d)
	mkdir /tmp/priv/$a
	mkdir /tmp/priv/$a/.X11-unix
	ln /tmp/.X11-unix/X999 /tmp/priv/$a/.X11-unix/X999
	args="$args $a:/tmp/priv/$a/sock"
	addcmd="nc -s 127.0.0.1 -p $pp -lke /bin/sh &"
	cat > /tmp/priv/$a/launch << EOF
#!/bin/sh
exec env -i DISPLAY=:999 HOME=/tmp PATH=/bin:/sbin:/usr/bin:/usr/sbin:/opt/R/bin LD_PRELOAD=libexecinfo.so R --vanilla -e 'p="/tmp/sock"; attr(p, "mask")=strtoi("117",8); shiny::runApp("app.R", port=p, launch.browser=F)' 
EOF
	chmod +x /tmp/priv/$a/launch
	unshare -rpmf /bin/sh -c "mount --bind /apps/$a /apps ; mount --bind /tmp/priv/$a /tmp ; cd /apps ; $addcmd exec unshare -Upfin /tmp/launch" &
#	(sleep 60 ; echo -en "GET / HTTP/1.1\r\n\r\n"|nc localhost 8080 > /tmp/cache/$a.html) &
	pp=$(($pp+1))
done
exec env -i /relayttpd 8080 $args

