#!/bin/sh
rm -rf /tmp/* /tmp/.*
rm -rf /var/run/*
[ -e /proc/self ] || mount -t proc none /proc
cat > /tmp/index.html << EOF
<!doctype html>
<meta name=viewport content=width=device-width>
<title>R/Shiny @ GdR MASCOT-NUM</title>
<a href=https://github.com/alex14fr/lagun-shiny-deploy/blob/master/README>README</a><p>
<a href=lagun/>LAGUN</a><p>
<a herf=terminal/>R terminal</a><p>
<!--
<a href=testapp/>Test application</a><p>
-->
<details><summary style=cursor:pointer>System info</summary>
<pre>
Server started $(date)
EOF
/opt/R/bin/R --vanilla -e "installed.packages()[,'Version']" >> /tmp/index.html
echo "</pre></details>" >> /tmp/index.html
mkdir /tmp/cache
Xvfb :999&
sleep 1
args=""
mkdir /tmp/priv
pp=1234
for d in /apps/* ; do
	[ -f $d/off ] && continue
	a=$(basename $d)
	mkdir /tmp/priv/$a
	mkdir /tmp/priv/$a/.X11-unix
	ln /tmp/.X11-unix/X999 /tmp/priv/$a/.X11-unix/X999
	args="$args $a:/tmp/priv/$a/x.sock"
#	addcmd="nc -s 127.0.0.1 -p $pp -lke /bin/sh &"
	if [ -e /apps/$a/launch ]; then
		cp /apps/$a/launch /tmp/priv/$a/launch
	else
		cat > /tmp/priv/$a/launch << EOF
#!/bin/sh
exec env -i DISPLAY=:999 HOME=/tmp PATH=/bin:/sbin:/usr/bin:/usr/sbin:/opt/R/bin LD_PRELOAD=libexecinfo.so R --vanilla -e 'p="/tmp/x.sock"; attr(p, "mask")=strtoi("117",8); shiny::runApp("app.R", port=p, launch.browser=F)' 
EOF
	fi
	chmod +x /tmp/priv/$a/launch
	if [ ! -e /apps/$a/launch0 ]; then
		unshare -rpmf /bin/sh -c "mount --bind /apps/$a /apps ; mount --bind /tmp/priv/$a /tmp ; cd /apps ; $addcmd exec unshare -Upfin /tmp/launch" &
	else
		cp /apps/$a/launch0 /tmp/priv/$a/launch0
		chmod a+x /tmp/priv/$a/launch0
		/tmp/priv/$a/launch0 &
	fi
	if [ ! -e /apps/$a/no_home_cache ]; then
		/httpget /tmp/priv/$a/x.sock 30 gzip > /tmp/cache/$a.html.gz &
		/httpget /tmp/priv/$a/x.sock 30 > /tmp/cache/$a.html &
	fi
	pp=$(($pp+1))
done
( while [ true ]; do sleep 3600;  find /tmp/priv/terminal/priv* -ctime +1 -delete; done ) &
exec env -i /relayttpd 8080 $args

