#!/bin/sh
rm -rf /tmp/* /tmp/.*
[ -e /proc/self ] || mount -t proc none /proc
umask 117
cat > /tmp/index.html << EOF
<!doctype html>
<meta name=viewport content=width=device-width>
<title>Shiny</title>
<a target=_blank href=lagun/>LAGUN</a><p>
<a target=_blank href=testapp/>Test application</a><p>
<details><summary>System info</summary>
<pre>
Server started $(date)
EOF
/opt/R/bin/R --vanilla -e "installed.packages()[,'Version']" >> /tmp/index.html
echo "</pre></details><p><a target=_blank href=https://github.com/alex14fr/lagun-shiny-deploy>Server source code</a>" >> /tmp/index.html
Xvfb :999&
args=""
for d in /apps/* ; do
	cd $d
	a=$(basename $d)
	mkdir /tmp/priv_$a
	args="$args $a:/tmp/priv_$a/sock"
	env -i DISPLAY=:999 HOME=/tmp PATH=/bin:/sbin:/usr/bin:/usr/sbin:/opt/R/bin LD_PRELOAD=libexecinfo.so unshare -Upmfn R --vanilla -e 'p="/tmp/priv_'$a'/sock"; attr(p,"mask"=strtoi("117",8)); shiny::runApp("app.R", port=p, launch.browser=F)' &
done
cd /
exec env -i /relayttpd 8080 $args

