#!/bin/sh
set -eux
cc -O3 -s -o relayttpd relayttpd.c
[ -d R-@RVER@ ] || tar xf R-@RVER@.tar.gz
cd R-@RVER@
[ -f Makefile ] || ./configure --prefix=/opt/R --with-readline=no --with-tcltk=yes --enable-java=no --enable-shared=no --with-ICU=no --disable-openmp --disable-nls --with-recommended-packages=no
make -j8
make install-strip

