#!/bin/sh
set -eux
[ -d R-@RVER@ ] || tar xf R-@RVER@.tar.gz
cd R-@RVER@
export CFLAGS=-O2
export CXXFLAGS=$CFLAGS
export F77FLAGS=$CFLAGS
[ -f Makefile ] || ./configure --prefix=/opt/R --with-readline=no --with-tcltk=no --enable-java=no --enable-shared=no --with-ICU=no --disable-openmp --disable-nls 
make -j8
make install-strip

